# Generated by Django 5.1.6 on 2025-08-19 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_user_phone_number_user_role_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='kyc_address',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='customers', to='systems.address'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='default_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_customers', to='systems.address'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='systems.address'),
            preserve_default=False,
        ),
    ]
